# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  # pre = "<i class=\"fas fa-book\" style=\"color: #007bff;\"></i>"
  name = "Pricing"
  url = "pricing/"
  weight = 40

[[main]]
  # pre = "<i class=\"fas fa-home\" style=\"color: #007bff;\"></i>"
  name = "Home"
  url = "#hero"
  weight = 10
  
[[main]]
  # pre = "<i class=\"fas fa-book\" style=\"color: #007bff;\"></i>"
  name = "Features"
  url = "#elements"
  weight = 20
  
# [[main]]
#   # pre = "<i class=\"fas fa-book\" style=\"color: #007bff;\"></i>"
#   name = "Blog"
#   url = "#posts"
#   weight = 40
  
[[main]]
  # pre = "<i class=\"fas fa-book\" style=\"color: #007bff;\"></i>"
  name = "Expo"
  url = "#expo"
  weight = 30
  
[[main]]
  # pre = "<i class=\"fas fa-book\" style=\"color: #007bff;\"></i>"
  name = "Contact"
  url = "#contact"
  weight = 60

# [[main]]
#   pre = "<i class=\"fas fa-newspaper\" style=\"color: #00d1b2;\"></i>"
#   name = "Updates"
#   url = "updates/"
#   weight = 70

# [[main]]
#   pre = "<i class=\"fas fa-brush\" style=\"color: #007bff;\"></i>"
#   name = "Themes"
#   url = "themes/"
#   weight = 80

# [[main]]
#   pre = "<i class=\"fas fa-donate\" style=\"color: #00d1b2;\"></i>"
#   name = "Support Academic"
#   url = "#support"
#   weight = 60

#[[main]]
#  pre = "<i class=\"fas fa-address-card\" style=\"color: #00d1b2;\"></i>"
#  name = "Widgets"
#  url = "widgets/"
#  weight = 70

# [[main_right]]
#   name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
#   post = ""
#   url = "https://github.com/gcushen/hugo-academic"
#   weight = 10

[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #38a1f3; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/websiteforvas"
  weight = 20
  
[[main_right]]
  name = "<i class=\"fab fa-facebook\" style=\"color: #3b5998; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://facebook.com/websiteforvas"
  weight = 30

[[main_right]]
  name = "<span class=\"btn btn-primary d-none d-lg-inline-block mb-0 mb-md-0 ml-md-0\">HIRE</span>"
  post = ""
  url = "#contact"
  weight = 40

# Documentation 

[[pricing]]
  name = "Pricing"
  weight = 5
  url = "/pricing/"

# [[pricing]]
#   name = "Basic"
#   weight = 10
#   identifier = "basic"

# [[pricing]]
#   name = "Premium"
#   weight = 20
#   identifier = "premium"

# [[docs]]
#   name = "Deployment"
#   weight = 30
#   identifier = "deploy"

# [[docs]]
#   name = "Migrate"
#   identifier = "migrate"
#   weight = 40

# [[docs]]
#   name = "Contributing"
#   url = "/docs/contribute/"
#   weight = 50

# [[docs]]
#   name = "Troubleshooting"
#   weight = 60
#   url = "/docs/faq/"
